FROM ubuntu:20.04 

ENV TOTAL_CHALLENGES=1000

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    build-essential \
    gcc \
    zip

WORKDIR /tmp
COPY src/requirements.txt ./
RUN pip3 install -r requirements.txt

COPY src/generate_challenges.py src/generate_stage_codes.py src/levels.py ./
COPY src/templates ./templates
